---
galaxy_info:
  role_name: vector
  author: EthDevOps
  description: Install and configure Vector for logs and metrics collection
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - vector
    - logging
    - metrics
    - observability
dependencies:
  - role: prometheus.prometheus.node_exporter
    when: vector_install_nodexporter
    vars:
      node_exporter_web_listen_address: "127.0.0.1:9100"
