---
- name: Make sure key dir exists
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings
- name: Get grafana apt key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
- name: Add grafana repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
  notify:
    - Update apt cache
- name: Install Grafana Agent Flow
  ansible.builtin.apt:
    name: grafana-agent-flow
- name: Create extra config dir
  ansible.builtin.file:
    state: directory
    path: /etc/grafana-targets.d
- name: Generate Grafana config file
  notify: Restart agent
  ansible.builtin.template:
    src: grafana-agent-flow.river
    dest: /etc/grafana-agent-flow.river
- name: Check if docker group exists
  ansible.builtin.command:
    cmd: getent group docker
  register: grafana_agent_docker_group_check
  failed_when: false
  changed_when: false
- name: Add user to docker group if group exists
  ansible.builtin.user:
    name: grafana-agent-flow
    groups: docker
    append: true
  when: grafana_agent_docker_group_check.rc == 0
- name: Make sure agent service is enabled
  ansible.builtin.systemd:
    name: grafana-agent-flow
    state: started
    enabled: true
