---
- name: Make sure agent service is stopped
  ansible.builtin.systemd:
    name: grafana-agent-flow
    state: stopped
    enabled: false
- name: Uninstall Grafana Agent Flow
  ansible.builtin.apt:
    name: grafana-agent-flow
    state: absent
- name: Remove grafana apt key
  ansible.builtin.file:
    path: /etc/apt/keyrings/grafana.asc
    state: absent
- name: Remove grafana repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    state: absent
- name: Remove extra config dir
  ansible.builtin.file:
    state: absent
    path: /etc/grafana-targets.d
- name: Remove Grafana config file
  ansible.builtin.file:
    path: /etc/grafana-agent-flow.river
    state: absent
