---
- name: Install JVB
  ansible.builtin.import_tasks: jvb.yaml
- name: Install exporter
  ansible.builtin.import_tasks: exporter.yaml
- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yaml
- name: Tune apt
  ansible.builtin.import_tasks: tune-apt.yaml
- name: Tune sysctl
  ansible.builtin.import_tasks: tune-sysctl.yaml
