---
- name: Configure sysctl tuning for JVB
  ansible.builtin.copy:
    dest: /etc/sysctl.d/21-jvb-tuning.conf
    content: |
      net.core.rmem_max=10485760
      net.core.wmem_max=10485760
      net.core.netdev_budget=600
      net.core.netdev_budget_usecs=16000
    owner: root
    group: root
    mode: "0644"
  notify: Apply sysctl settings
