---
galaxy_info:
  role_name: haproxy_lb
  author: EthDevOps
  description: Install and configure HAProxy load balancer
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - haproxy
    - loadbalancer
    - proxy
    - networking
dependencies: []
