---
galaxy_info:
  role_name: docker_debian
  author: EthDevOps
  description: Install Docker on Debian-based systems
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - docker
    - containers
    - debian
dependencies: []
