---
vector_extra_metrics: ""
vector_install_nodexporter: true
vector_version: "0.51.1-1"
vector_use_openbao: false

# OpenBao/Vault secret configuration
vector_vault_secret_path: "secret/common/metric_ingress"
vector_vault_user_field: "metrics_username"
vector_vault_password_field: "metrics_password"
