---
- name: Copy systemd service file
  ansible.builtin.copy:
    src: servermode.service
    dest: /etc/systemd/system/server-mode.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
- name: Enable and start the service
  ansible.builtin.systemd:
    name: server-mode
    state: started
    enabled: true
- name: Set kernel parameters in /etc/default/grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="intel_iommu=on iommu=pt"'
    backup: true
  notify:
    - Update GRUB
